apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service 
  labels:
      app: ft-services
spec:
  type: ClusterIP
  selector:
      app: mysqlapp
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
      app: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      labels:
        app: mysqlapp
    spec:
      containers:
      - name: mysql
        image: my_mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
